project:
  type: book
  output-dir: docs

book:
  title: "dashboard project"
  author: "jinha"
  date: "2024. 3. 25."
  sidebar: 
    style: docked
    background: light
    collapse-level: 1
    alignment: left
    foreground: primary
    search: true
  chapters:
    - index.qmd
    - part: "SETTING & BASIC"
      chapters:
        - 0101-Rstudio_cloud.qmd
        - 0103-DataVisualization.qmd
    - part: "FLEXDASHBOARD"
      chapters:
        - 0201-flexdashboard.qmd
        - 0251-flexdashboard_datatable.qmd
    - part: "SHINY"
      chapters:
        - 0401-shiny.qmd
        - 0451-shiny_phq.qmd
        - 0461-shiny_html.qmd
    - part: "Map visualization"
      chapters: 
        - 0510-maps.qmd
        - 0520-leaflet_maps_korea.qmd
        - 0530-leaflet_maps_shiny.qmd
    - part : "Prediction Model App"
      chapters: 
        - 0610-prediction_model.qmd
        - 0650-change_point_model.qmd
        
    - part : "Google data"
      chapters: 
        - 0710-Google_model.qmd

        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    #css: style.css
  pdf:
    documentclass: scrreprt
    prefer-html: true

editor: source
